#!/usr/bin/node

//TODO: HANDLE SERVER EVENTS (ONLISTENING, ONERROR, ETC) & SIGNALS (SIGNALS LIKE SIGHUP, SIGINT)

require("dotenv").config();

var debug = require('debug')('react-app:server');
var http = require('http');

const app = require("./app");

var port = normalizePort(process.env.PORT || '3000');
app.set('port', port);

//Create HTTP server.
const server = http.createServer(app);

//connect to DB
const {sequelize} = require("./database/models/index");

function connect() {
  return new Promise(async (resolve, reject) => {
	try {
	//Conectando ao servidor MariaDB
    await sequelize.authenticate();

	//Sincronizar models & tabelas
	await sequelize.sync()
	/*
    app.listen(process.env.PORT, () => {
      console.log(`🚀 Backend rodando na porta ${process.env.PORT}`);
    });
	*/
	resolve()
  } catch (err) {
    reject(err);
  }
	})
}

server.on('error', onError);
//server.on('listening', onListening);

connect()
	.then(() => {
		//Listen on provided port, on all network interfaces
		server.listen(port);
		console.log('\n[*] Servidor rodando na porta ' + port)
	})
	.catch(err => {
		console.error('[!] Erro ao iniciar o servidor: ' + err.message)
		console.error(err)
	})

//Normalize a port into a number, string, or false.
function normalizePort(val) {
  var port = parseInt(val, 10);

  if (isNaN(port)) {// named pipe
    return val;
  }

  if (port >= 0) {// port number
    return port;
  }

  return false;
}

// Event listener for HTTP server "error" event.
function onError(error) {
  if (error.syscall !== 'listen') {
    throw error;
  }

  var bind = typeof port === 'string'
    ? 'Pipe ' + port
    : 'Port ' + port;

  // handle specific listen errors with friendly messages
  switch (error.code) {
    case 'EACCES':
      console.error(bind + ' requer privilégios elevados');
      process.exit(1);
      break;
    case 'EADDRINUSE':
      console.error(bind + ' já está em uso');
      process.exit(1);
      break;
    default:
      throw error;
  }
}

// Event listener for HTTP server "listening" event.
function onListening() {
  var addr = server.address();
  var bind = typeof addr === 'string'
    ? 'pipe ' + addr
    : 'port ' + addr.port;

  debug('Servidor em execução na porta' + bind);
}
